import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useDispatch, useSelector } from "react-redux";


function Checkout({ onConfirmOrder }) {
  const [customerName, setCustomerName] = useState('');
  const [customerNumber, setCustomerNumber] = useState('');
  const [email, setEmail] = useState('');
  const [shippingAddress, setShippingAddress] = useState('');


  const navigate = useNavigate();
  const dispatch = useDispatch();
  function EmptyCart(){
    console.log("EmptyCart");
    dispatch({type:"EMPTYCART"});
}

  const handleConfirmOrder = () => {
    let orderid=Math.random()*100000;
    const orderData = {
      customerName,
      customerNumber,
      email,
      shippingAddress
    };
    // Call the onConfirmOrder function with order data which put data in ordertable

    //onConfirmOrder(orderData);
    alert(`orderdid:${orderid}(autogenerated)`);

    //Empty the cart
    EmptyCart();

    navigate('/');
  };

  return (
    <div>
      <h2>Order Form</h2>
      <div>
        <label>Customer Name:</label>
        <input type="text" value={customerName} onChange={(e) => setCustomerName(e.target.value)} />
      </div>
      <div>
        <label>Customer Number:</label>
        <input type="text" value={customerNumber} onChange={(e) => setCustomerNumber(e.target.value)} />
      </div>
      <div>
        <label>Email:</label>
        <input type="text" value={email} onChange={(e) => setEmail(e.target.value)} />
      </div>
      <div>
        <label>Shipping Address:</label>
        <textarea value={shippingAddress} onChange={(e) => setShippingAddress(e.target.value)} />
      </div>
      <button onClick={handleConfirmOrder}>Confirm Order</button>
    </div>
  );
}

export default Checkout;
